In [ ]:
!pip install boto3 pandas geopandas shapely fiona h3 requests psutil

In [1]:
import boto3
import json
import time

## Data Extraction

In [2]:
# AWS LOGINS
session = boto3.Session(
    aws_access_key_id="AKIAYH57YDEWMHW2ESH2",
    aws_secret_access_key="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",
    region_name="af-south-1"
)

s3 = session.client("s3") # S3 BUCKET

bucket = "cct-ds-code-challenge-input-data"
key = "city-hex-polygons-8-10.geojson"

# AWS SELECT STATEMENT
expression = "SELECT * FROM S3Object s WHERE s.resolution = '8'"  # using the  select statement didn't help me much, I ran into errors ,

In [3]:
start = time.time()

In [4]:
s_3 = session.client("s3")
bucket = "cct-ds-code-challenge-input-data"
key = "city-hex-polygons-8-10.geojson"

# Download file
obj = s_3 .get_object(Bucket=bucket, Key=key)
data = json.loads(obj['Body'].read())

because the select statement wasn't working to my advantage; I filtered through the data using python syntax
I chnaged the properties column to a str so that i can be able  get resolution 8 data properly

In [5]:
# Filter features with resolution = 8
features_res8 = [
    f for f in data["features"]
    if str(f["properties"].get("resolution")) == "8"
]

In [7]:
len(features_res8) # checking number of rows found here

3832

In [8]:
print(features_res8[0])

{'type': 'Feature', 'properties': {'index': '88ad361801fffff', 'centroid_lat': -33.859427322761434, 'centroid_lon': 18.677843311941835, 'resolution': 8}, 'geometry': {'type': 'Polygon', 'coordinates': [[[18.6811898997334, -33.86330279081797], [18.683574296194426, -33.85928287732969], [18.68022760998973, -33.85540739558428], [18.67449676770625, -33.855551865779326], [18.672112346191998, -33.85957172360946], [18.675458791982372, -33.8634471669068], [18.6811898997334, -33.86330279081797]]]}}

Making t

In [9]:
import geopandas as gpd
from shapely.geometry import shape

# Convert features into a list of dicts (properties + geometry)
records = []
for f in features_res8:
    props = f["properties"].copy()  # copy properties dict
    props["geometry"] = shape(f["geometry"])  # shapely polygon
    records.append(props)

# Create GeoDataFrame
geodf = gpd.GeoDataFrame(records, geometry="geometry")

INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [10]:
geodf.head(10000)

,index,centroid_lat,centroid_lon,resolution,geometry
0,88ad361801fffff,-33.859427,18.677843,8,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,8,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,8,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,8,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,8,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,8,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,8,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,8,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,8,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,8,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

This is the validation, what we call "source of truth"

In [11]:
bucket2 = "cct-ds-code-challenge-input-data"
key2 = "city-hex-polygons-8.geojson"
out_file = "city-hex-polygons-8.geojson"

s3.download_file(bucket2, key2, out_file)

In [12]:
#import geopandas as valid_df
valid_df = gpd.read_file("city-hex-polygons-8.geojson")
valid_df.head(10000)

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

### Data validation

for starters: The data I xtracted from aws and the validation data they have the same number of row

In [13]:
# taking the column names that are the same as my validation set
extract_df = geodf[['index', 'centroid_lat', 'centroid_lon', 'geometry']]

In [14]:
extract_df

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

In [15]:
valid_df

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

I then used an inner join to check if we have similar data with the validation set

In [16]:
common = extract_df.merge(valid_df, how='inner')
print(f"{len(common)} rows in aws extract are also in validation extract")
#common.head()

3832 rows in aws extract are also in validation extract

an extra check for those not on the other and now I switched data around

In [17]:
valid_df.geometry

0       POLYGON ((18.68119 -33.8633, 18.68357 -33.8592...
1       POLYGON ((18.67211 -33.85957, 18.6745 -33.8555...
2       POLYGON ((18.68931 -33.85914, 18.69169 -33.855...
3       POLYGON ((18.68023 -33.85541, 18.68261 -33.851...
4       POLYGON ((18.68215 -33.8712, 18.68454 -33.8671...
                              ...
3827    POLYGON ((18.48255 -34.35726, 18.48494 -34.353...
3828    POLYGON ((18.47346 -34.35353, 18.47585 -34.349...
3829    POLYGON ((18.48063 -34.34158, 18.48303 -34.337...
3830    POLYGON ((18.49068 -34.35315, 18.49307 -34.349...
3831    POLYGON ((18.48159 -34.34942, 18.48398 -34.345...
Name: geometry, Length: 3832, dtype: geometry

In [18]:
diff = valid_df[~valid_df['index'].isin(extract_df['index'])]
print(f"{len(diff)} rows in the aws extract are NOT in validation data")

0 rows in the aws extract are NOT in validation data

## Initial Transformation

In [19]:
import pandas as pd

In [20]:
df_sr = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr.csv")

In [21]:
df_sr.head()

,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude
0,0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488
1,1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940
2,2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116
3,3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209
4,4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760

In [22]:
merged_df2 = extract_df.merge(
    df_sr,
    left_on=['centroid_lat', 'centroid_lon'],
    right_on=['latitude', 'longitude'],
    how='inner'
)

In [23]:
merged_df2

Empty GeoDataFrame
Columns: [index, centroid_lat, centroid_lon, geometry, Unnamed: 0, notification_number, reference_number, creation_timestamp, completion_timestamp, directorate, department, branch, section, code_group, code, cause_code_group, cause_code, official_suburb, latitude, longitude]
Index: []

In [24]:
print(extract_df.iloc[0].geometry)

POLYGON ((18.6811898997334 -33.86330279081797, 18.683574296194426 -33.85928287732969, 18.68022760998973 -33.85540739558428, 18.67449676770625 -33.855551865779326, 18.672112346191998 -33.85957172360946, 18.675458791982372 -33.8634471669068, 18.6811898997334 -33.86330279081797))

In [25]:
rows = []
for i, row in extract_df.iterrows():
    polygon = row.geometry
    for lon, lat in polygon.exterior.coords:   
        rows.append({
            "index": row["index"],             
            "longitude": lon,
            "latitude": lat
        })

coords_df = pd.DataFrame(rows)

In [26]:
coords_df

                 index  longitude   latitude
0      88ad361801fffff  18.681190 -33.863303
1      88ad361801fffff  18.683574 -33.859283
2      88ad361801fffff  18.680228 -33.855407
3      88ad361801fffff  18.674497 -33.855552
4      88ad361801fffff  18.672112 -33.859572
...                ...        ...        ...
26819  88ad36973bfffff  18.480635 -34.341576
26820  88ad36973bfffff  18.474896 -34.341703
26821  88ad36973bfffff  18.472504 -34.345687
26822  88ad36973bfffff  18.475851 -34.349546
26823  88ad36973bfffff  18.481590 -34.349420

[26824 rows x 3 columns]

In [27]:
merged_df3 = coords_df.merge(
    df_sr,
    on=["longitude", "latitude"],
    how="inner"
)

In [28]:
merged_df3.head

<bound method NDFrame.head of Empty DataFrame
Columns: [index, longitude, latitude, Unnamed: 0, notification_number, reference_number, creation_timestamp, completion_timestamp, directorate, department, branch, section, code_group, code, cause_code_group, cause_code, official_suburb]
Index: []>

new

In [29]:
from shapely.geometry import Point
import time, logging

logging.basicConfig(level=logging.INFO)

start_time = time.time()


requests_df = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr.csv")        # service requests

# 2. Make requests GeoDataFrame
requests_gdf = gpd.GeoDataFrame(
    requests_df,
    geometry=[Point(xy) if pd.notna(xy[0]) and pd.notna(xy[1]) else None 
              for xy in zip(requests_df["longitude"], requests_df["latitude"])],
    crs="EPSG:4326"
)

In [30]:
valid_df = valid_df[["index","geometry"]].copy()
requests_gdf = requests_gdf[["geometry"] + [col for col in requests_gdf.columns if col != "geometry"]]

joined = gpd.sjoin(requests_gdf, valid_df, how="left", predicate="within")

In [31]:
joined

,geometry,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,index_right0,index
0,POINT (18.52249 -33.87284),0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488,1047.0,88ad360225fffff
1,POINT (18.84894 -34.07892),1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940,3055.0,88ad36d5e1fffff
2,POINT (18.82112 -34.10224),2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116,2946.0,88ad36d437fffff
3,POINT (18.60721 -33.92002),3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209,1247.0,88ad361133fffff
4,POINT (18.45376 -33.9874),4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760,2530.0,88ad361709fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941629,POINT (18.45216 -33.93157),941629,1016508425,9.109974e+09,2020-12-31 23:49:38+02:00,2021-01-11 11:54:42+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,WOODSTOCK,-33.931571,18.452159,2439.0,88ad361547fffff
941630,POINT (18.71655 -33.78325),941630,1016508432,9.109975e+09,2020-12-31 23:31:11+02:00,2021-01-04 11:46:28+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,FISANTEKRAAL,-33.783246,18.716554,542.0,88ad3656d7fffff
941631,None,941631,1016508434,9.109975e+09,2020-12-31 23:58:21+02:00,2021-01-01 00:01:08+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,WATER,Burst Pipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941632,POINT (18.65983 -33.9711),941632,1016508442,9.109975e+09,2020-12-31 23:41:57+02:00,2021-01-05 15:59:24+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,WESBANK,-33.971099,18.659831,1502.0,88ad36c49bfffff
941633,POINT (18.86255 -34.08808),941633,1016508443,9.109975e+09,2020-12-31 23:54:09+02:00,2021-02-23 10:38:21+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER,Leak at Water Meter / Stopcock,NaN,NaN,BIZWENI,-34.088078,18.862550,2974.0,88ad36d517fffff

### data validation

In [32]:
df_val = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr_hex.csv")

In [33]:
df_val

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index
0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488,88ad360225fffff
1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940,88ad36d5e1fffff
2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116,88ad36d437fffff
3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209,88ad361133fffff
4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760,88ad361709fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941629,1016508425,9.109974e+09,2020-12-31 23:49:38+02:00,2021-01-11 11:54:42+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,WOODSTOCK,-33.931571,18.452159,88ad361547fffff
941630,1016508432,9.109975e+09,2020-12-31 23:31:11+02:00,2021-01-04 11:46:28+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,FISANTEKRAAL,-33.783246,18.716554,88ad3656d7fffff
941631,1016508434,9.109975e+09,2020-12-31 23:58:21+02:00,2021-01-01 00:01:08+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,WATER,Burst Pipe,NaN,NaN,NaN,NaN,NaN,0
941632,1016508442,9.109975e+09,2020-12-31 23:41:57+02:00,2021-01-05 15:59:24+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,WESBANK,-33.971099,18.659831,88ad36c49bfffff
941633,1016508443,9.109975e+09,2020-12-31 23:54:09+02:00,2021-02-23 10:38:21+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER,Leak at Water Meter / Stopcock,NaN,NaN,BIZWENI,-34.088078,18.862550,88ad36d517fffff

In [34]:
merged_df4 = df_val.merge(
    joined,
    on=["notification_number"],
    how="inner"
)

In [35]:
print(f"{len(merged_df4)} rows in joined data are also in validation extract")

941634 rows in joined data are also in validation extract

## Further transformations

### one minute away from bellville

use the valisation set to find  belville locations

In [36]:
sr_hex =df_val

In [37]:
bellville = sr_hex[sr_hex["official_suburb"] == "BELLVILLE SOUTH"]

In [38]:
bellville

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index
22,400586554,9.109558e+09,2020-10-16 14:41:42+02:00,2020-10-26 14:15:30+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Manhole Cover/Gully Grid,NaN,NaN,BELLVILLE SOUTH,-33.918566,18.639464,88ad361127fffff
77,400561576,9.109113e+09,2020-07-31 09:52:09+02:00,2020-08-10 11:47:25+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Block Pipe/Chan/Canal/Drain/Gully/Manh,NaN,NaN,BELLVILLE SOUTH,-33.914229,18.634373,88ad361ac9fffff
112,400587935,NaN,2020-10-22 07:05:20+02:00,2020-10-26 14:16:49+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,BELLVILLE SOUTH,-33.911623,18.637918,88ad361acdfffff
158,400575630,9.109346e+09,2020-09-11 12:14:07+02:00,2021-02-04 12:57:46+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,BELLVILLE SOUTH,-33.920465,18.646942,88ad361127fffff
175,400586642,NaN,2020-10-17 18:00:45+02:00,2020-10-26 14:15:30+02:00,NaN,NaN,NaN,NaN,TD Customer complaint groups,Contam Spill / Rock mud verge collapsing,NaN,NaN,BELLVILLE SOUTH,-33.920501,18.651917,88ad361125fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940708,1016507398,NaN,2020-12-31 11:22:29+02:00,2021-01-07 12:58:10+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Stopcock: Defective,Loss,No Cause Observed,BELLVILLE SOUTH,-33.920660,18.639745,88ad361127fffff
940878,1016507581,9.109973e+09,2020-12-31 11:57:42+02:00,2021-01-01 11:53:17+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,BELLVILLE SOUTH,-33.915132,18.639729,88ad361acdfffff
940948,1016507656,9.109974e+09,2020-12-31 12:29:29+02:00,2021-01-01 11:54:32+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,BELLVILLE SOUTH,-33.919625,18.648965,88ad361125fffff
941453,1016508221,9.109974e+09,2020-12-31 18:56:43+02:00,2020-12-31 20:09:12+02:00,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,None/Private,BELLVILLE SOUTH,-33.921359,18.641689,88ad361127fffff
941571,1016508355,9.109974e+09,2020-12-31 21:02:26+02:00,2021-01-07 12:59:36+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,Loss,No Cause Observed,BELLVILLE SOUTH,-33.920207,18.637990,88ad361127fffff

So I will take average of eeach longitude  and latitude 
then conver what 1km is in degerres or what 1 min away is  in degrees

In [39]:
centroid_lat = bellville["latitude"].mean()
centroid_lon = bellville["longitude"].mean()

In [40]:
print(centroid_lat,centroid_lon)

-33.91701852446488 18.64198443299487

it seems using the geo distance is more accurate, however not sure if I would be able to accurately present on i. 
so using one minute away conversion make

### How I calculated distance



The dataset gives latitude and longitude, but you can’t just subtract those to get distance (because the size of a degree changes depending on where you are on Earth).  

To handle this properly, I used the Haversine formula, which is a standard way to calculate the shortest distance between two points on the Earth’s surface.  

The idea is:
- Convert both points (lat/lon) into radians.
- Work out the differences in latitude and longitude.
- Use some basic trigonometry to figure out the great-circle distance (the “as-the-crow-flies” distance on a sphere).
- Multiply that by the Earth’s radius (about 6371 km) to get the distance in kilometers.

In simple terms:  
I’m just calculating how far each service request is from the centroid of Bellville South, and then I keep only the ones that fall within about **1.85 km** (which is roughly equal to 1 minute of latitude).

In [41]:
import math

In [42]:
# Haversine distance in km
def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0  
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = math.sin(dphi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

In [43]:
centroid = (centroid_lat, centroid_lon)

In [44]:
radius_km = 1.852

calcluating the distance between each point

In [ ]:
sr_hex["dist_to_centroid"] = sr_hex.apply(
    lambda row: haversine(centroid_lat, centroid_lon, row["latitude"], row["longitude"]), axis=1)

In [46]:
subsample = sr_hex[sr_hex["dist_to_centroid"] <= radius_km].copy()

The data of the placeses  1 min away from bellvile

In [47]:
subsample

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index,dist_to_centroid
6,400588369,NaN,2020-10-23 10:33:48+02:00,2020-10-26 14:16:49+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,GLENHAVEN,-33.917996,18.658031,88ad361a19fffff,1.484676
15,400589257,9.109617e+09,2020-10-27 11:36:55+02:00,2020-11-11 07:39:11+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,SACK'S CIRCLE INDUSTRIA,-33.924853,18.654994,88ad361125fffff,1.483197
22,400586554,9.109558e+09,2020-10-16 14:41:42+02:00,2020-10-26 14:15:30+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Manhole Cover/Gully Grid,NaN,NaN,BELLVILLE SOUTH,-33.918566,18.639464,88ad361127fffff,0.289354
68,400598644,NaN,2020-12-01 10:28:54+02:00,2021-02-05 08:11:05+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,KEMPENVILLE,-33.901597,18.636384,88ad361ac5fffff,1.790969
73,400554944,NaN,2020-07-09 14:42:01+02:00,2020-07-16 10:31:11+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Flooding Road/Property/Informal Set,NaN,NaN,BELLVILLE CBD,-33.904904,18.632356,88ad361ac1fffff,1.613719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940948,1016507656,9.109974e+09,2020-12-31 12:29:29+02:00,2021-01-01 11:54:32+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,BELLVILLE SOUTH,-33.919625,18.648965,88ad361125fffff,0.706281
940950,1016507658,9.109974e+09,2020-12-31 12:29:54+02:00,2021-01-08 09:37:41+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Debt Management,NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681
941054,1016507773,9.109974e+09,2020-12-31 12:40:49+02:00,2021-01-11 15:34:51+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Reconnect (Non - Payment),NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681
941453,1016508221,9.109974e+09,2020-12-31 18:56:43+02:00,2020-12-31 20:09:12+02:00,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,None/Private,BELLVILLE SOUTH,-33.921359,18.641689,88ad361127fffff,0.483362
941571,1016508355,9.109974e+09,2020-12-31 21:02:26+02:00,2021-01-07 12:59:36+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,Loss,No Cause Observed,BELLVILLE SOUTH,-33.920207,18.637990,88ad361127fffff,0.511469

### wind speed data

#### wind data cleaning ,  the data was throughly cleaned to be used for joining. 
  The cleaning  includes:  
  - reading the data as an odf file
                          
   - removing the first row as it had unnamed as the first column 
   -removing the first 2 rows of the data as they  were empty 
   - renaming column names after the deletion 
   - converting timestamp dat to be the same as the  substet data type for time 
   - created a susbet for just bellvile columns since susbset is only for belville and neighboring. 
   - made the column names to be numeric

so the document actually isn in ods

In [ ]:
wind=pd.read_excel(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\Wind_direction_and_speed_2020.ods",engine='odf')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 14: invalid start byte

In [49]:
    pip install pandas odfpy

Requirement already satisfied: pandas in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Collecting odfpy
  Downloading odfpy-1.4.1.tar.gz (717 kB)
     ---------------------------------------- 0.0/717.0 kB ? eta -:--:--
     - ----------------------------------- 20.5/717.0 kB 330.3 kB/s eta 0:00:03
     --- --------------------------------- 71.7/717.0 kB 787.7 kB/s eta 0:00:01
     --------------- ---------------------- 286.7/717.0 kB 2.2 MB/s eta 0:00:01
     --------------------- ---------------- 399.4/717.0 kB 2.3 MB/s eta 0:00:01
     ----------------------------- -------- 553.0/717.0 kB 2.5 MB/s eta 0:00:01
     ------------------------------------ - 686.1/717.0 kB 2.7 MB/s eta 0:00:01
     -------------------------------------- 717.0/717.0 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.26.0 in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: defusedxml in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from odfpy) (0.7.1)
Requirement already satisfied: six>=1.5 in c:\users\yomelelalornamgwebi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Building wheels for collected packages: odfpy
  Building wheel for odfpy (setup.py): started
  Building wheel for odfpy (setup.py): finished with status 'done'
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=137515 sha256=6cc507f4a67eb92a943fe76a95f9fe8a550c4fc0063b1c9a6d0fc61dc5cd4670
  Stored in directory: c:\users\yomelelalornamgwebi\appdata\local\pip\cache\wheels\36\5d\63\8243a7ee78fff0f944d638fd0e66d7278888f5e2285d7346b6
Successfully built odfpy
Installing collected packages: odfpy
Successfully installed odfpy-1.4.1

In [50]:
wind=pd.read_excel(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\Wind_direction_and_speed_2020.ods",engine='odf')

In [51]:
wind

,MultiStation: Periodically: 01/01/2020 00:00-31/12/2020 23:59 Type: AVG 1 Hr.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Date & Time,Atlantis AQM Site,Atlantis AQM Site,Bellville South AQM Site,Bellville South AQM Site,Bothasig AQM Site,Bothasig AQM Site,Goodwood AQM Station,Goodwood AQM Station,Khayelitsha AQM Site,Khayelitsha AQM Site,Somerset West AQM Site,Somerset West AQM Site,Tableview AQM Site,Tableview AQM Site
2,NaN,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V
3,NaN,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s
4,01/01/2020 00:00,173,4.1,191,2.5,163.7,5.3,247.8,19.2,34.2,1.3,135,3.8,179.8,5.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8791,MaxDate,11/01/2020 04:00,17/01/2020 15:00,11/12/2020 21:00,13/07/2020 12:00,16/10/2020 23:00,01/10/2020 13:00,04/05/2020 08:00,09/07/2020 00:00,30/10/2020 01:00,01/10/2020 16:00,01/01/2020 03:00,25/01/2020 14:00,14/03/2020 01:00,13/07/2020 00:00
8792,Avg,188.8,4,216.9,2,175.5,3.6,293.1,14,38.1,0.7,176.9,3,185.7,3.6
8793,Num,2324,2324,7390,8531,8434,8434,8636,8118,7451,7451,842,842,8629,8629
8794,Data[%],26.5,26.5,84.1,97.1,96,96,98.3,92.4,84.8,84.8,9.6,9.6,98.2,98.2
8795,STD,67,1.9,No Data,1.1,110.3,2.2,No Data,9.8,12.1,0.4,102.5,1.8,66.4,1.8

I will make the second row  as a heading

In [72]:
wind = pd.read_excel(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\Wind_direction_and_speed_2020.ods",engine='odf',header=2 )

In [73]:
wind

,Date & Time,Atlantis AQM Site,Atlantis AQM Site.1,Bellville South AQM Site,Bellville South AQM Site.1,Bothasig AQM Site,Bothasig AQM Site.1,Goodwood AQM Station,Goodwood AQM Station.1,Khayelitsha AQM Site,Khayelitsha AQM Site.1,Somerset West AQM Site,Somerset West AQM Site.1,Tableview AQM Site,Tableview AQM Site.1
0,NaN,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V,Wind Dir V,Wind Speed V
1,NaN,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s,Deg,m/s
2,01/01/2020 00:00,173,4.1,191,2.5,163.7,5.3,247.8,19.2,34.2,1.3,135,3.8,179.8,5.2
3,01/01/2020 01:00,177.7,4,209.7,1.6,159,5.4,247,17.9,34.9,1.1,132.7,2.1,177.9,5.2
4,01/01/2020 02:00,180.7,2.8,202.5,1.4,148.8,5.5,246.4,17.1,35.5,1.1,128.5,2.4,167.8,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8789,MaxDate,11/01/2020 04:00,17/01/2020 15:00,11/12/2020 21:00,13/07/2020 12:00,16/10/2020 23:00,01/10/2020 13:00,04/05/2020 08:00,09/07/2020 00:00,30/10/2020 01:00,01/10/2020 16:00,01/01/2020 03:00,25/01/2020 14:00,14/03/2020 01:00,13/07/2020 00:00
8790,Avg,188.8,4,216.9,2,175.5,3.6,293.1,14,38.1,0.7,176.9,3,185.7,3.6
8791,Num,2324,2324,7390,8531,8434,8434,8636,8118,7451,7451,842,842,8629,8629
8792,Data[%],26.5,26.5,84.1,97.1,96,96,98.3,92.4,84.8,84.8,9.6,9.6,98.2,98.2
8793,STD,67,1.9,No Data,1.1,110.3,2.2,No Data,9.8,12.1,0.4,102.5,1.8,66.4,1.8

In [74]:
print(wind.columns.tolist())

['Date & Time', 'Atlantis AQM Site', 'Atlantis AQM Site.1', 'Bellville South AQM Site', 'Bellville South AQM Site.1', 'Bothasig AQM Site', 'Bothasig AQM Site.1', 'Goodwood AQM Station', 'Goodwood AQM Station.1', 'Khayelitsha AQM Site', 'Khayelitsha AQM Site.1', 'Somerset West AQM Site', 'Somerset West AQM Site.1', 'Tableview AQM Site', 'Tableview AQM Site.1']

the only thing close to unique i can join on is date and time

In [77]:
wind.iloc[0]

Date & Time                            NaN
Atlantis AQM Site               Wind Dir V
Atlantis AQM Site.1           Wind Speed V
Bellville South AQM Site        Wind Dir V
Bellville South AQM Site.1    Wind Speed V
Bothasig AQM Site               Wind Dir V
Bothasig AQM Site.1           Wind Speed V
Goodwood AQM Station            Wind Dir V
Goodwood AQM Station.1        Wind Speed V
Khayelitsha AQM Site            Wind Dir V
Khayelitsha AQM Site.1        Wind Speed V
Somerset West AQM Site          Wind Dir V
Somerset West AQM Site.1      Wind Speed V
Tableview AQM Site              Wind Dir V
Tableview AQM Site.1          Wind Speed V
Name: 0, dtype: object

In [78]:
wind = wind.drop(0).reset_index(drop=True)

In [82]:
wind=wind.drop(0).reset_index(drop=True)

In [83]:
wind

,Date & Time,Atlantis AQM Site,Atlantis AQM Site.1,Bellville South AQM Site,Bellville South AQM Site.1,Bothasig AQM Site,Bothasig AQM Site.1,Goodwood AQM Station,Goodwood AQM Station.1,Khayelitsha AQM Site,Khayelitsha AQM Site.1,Somerset West AQM Site,Somerset West AQM Site.1,Tableview AQM Site,Tableview AQM Site.1
0,01/01/2020 00:00,173,4.1,191,2.5,163.7,5.3,247.8,19.2,34.2,1.3,135,3.8,179.8,5.2
1,01/01/2020 01:00,177.7,4,209.7,1.6,159,5.4,247,17.9,34.9,1.1,132.7,2.1,177.9,5.2
2,01/01/2020 02:00,180.7,2.8,202.5,1.4,148.8,5.5,246.4,17.1,35.5,1.1,128.5,2.4,167.8,4
3,01/01/2020 03:00,183.7,2.3,224.7,1.2,153,4.7,245.1,15.7,35.5,1,357.6,1.1,177.3,4.4
4,01/01/2020 04:00,170.7,2.4,244.3,1.3,153.4,4.1,249.9,15.8,35.1,0.8,319.5,1.4,178.7,3.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8787,MaxDate,11/01/2020 04:00,17/01/2020 15:00,11/12/2020 21:00,13/07/2020 12:00,16/10/2020 23:00,01/10/2020 13:00,04/05/2020 08:00,09/07/2020 00:00,30/10/2020 01:00,01/10/2020 16:00,01/01/2020 03:00,25/01/2020 14:00,14/03/2020 01:00,13/07/2020 00:00
8788,Avg,188.8,4,216.9,2,175.5,3.6,293.1,14,38.1,0.7,176.9,3,185.7,3.6
8789,Num,2324,2324,7390,8531,8434,8434,8636,8118,7451,7451,842,842,8629,8629
8790,Data[%],26.5,26.5,84.1,97.1,96,96,98.3,92.4,84.8,84.8,9.6,9.6,98.2,98.2
8791,STD,67,1.9,No Data,1.1,110.3,2.2,No Data,9.8,12.1,0.4,102.5,1.8,66.4,1.8

In [84]:
wind_subset = wind[["Date & Time","Bellville South AQM Site","Bellville South AQM Site.1"]].copy()

In [85]:
# renaming because i droped the idetifiers
wind_subset = wind_subset.rename(columns={"Date & Time": "timestamp", "Bellville South AQM Site": "bellville_wind_dir","Bellville South AQM Site.1": "bellville_wind_speed"})

In [86]:
wind_subset["timestamp"] = pd.to_datetime(wind_subset["timestamp"], errors="coerce")

In [87]:
wind_subset

               timestamp bellville_wind_dir bellville_wind_speed
0    2020-01-01 00:00:00                191                  2.5
1    2020-01-01 01:00:00              209.7                  1.6
2    2020-01-01 02:00:00              202.5                  1.4
3    2020-01-01 03:00:00              224.7                  1.2
4    2020-01-01 04:00:00              244.3                  1.3
...                  ...                ...                  ...
8787                 NaT   11/12/2020 21:00     13/07/2020 12:00
8788                 NaT              216.9                    2
8789                 NaT               7390                 8531
8790                 NaT               84.1                 97.1
8791                 NaT            No Data                  1.1

[8792 rows x 3 columns]

In [88]:
wind_subset = wind_subset.dropna(subset=["timestamp"])

In [89]:
wind_subset

               timestamp bellville_wind_dir bellville_wind_speed
0    2020-01-01 00:00:00                191                  2.5
1    2020-01-01 01:00:00              209.7                  1.6
2    2020-01-01 02:00:00              202.5                  1.4
3    2020-01-01 03:00:00              224.7                  1.2
4    2020-01-01 04:00:00              244.3                  1.3
...                  ...                ...                  ...
8323 2020-12-12 19:00:00              171.3                  2.3
8324 2020-12-12 20:00:00              174.2                  2.1
8325 2020-12-12 21:00:00              194.6                  1.8
8326 2020-12-12 22:00:00              223.9                    1
8327 2020-12-12 23:00:00              236.6                  1.2

[3456 rows x 3 columns]

In [ ]:
# keeping only numeric and none null values
wind_subset = wind_subset[
    pd.to_numeric(wind_subset["bellville_wind_dir"], errors="coerce").notna() &
    pd.to_numeric(wind_subset["bellville_wind_speed"], errors="coerce").notna()
]

In [91]:
wind_subset

               timestamp bellville_wind_dir bellville_wind_speed
0    2020-01-01 00:00:00                191                  2.5
1    2020-01-01 01:00:00              209.7                  1.6
2    2020-01-01 02:00:00              202.5                  1.4
3    2020-01-01 03:00:00              224.7                  1.2
4    2020-01-01 04:00:00              244.3                  1.3
...                  ...                ...                  ...
8323 2020-12-12 19:00:00              171.3                  2.3
8324 2020-12-12 20:00:00              174.2                  2.1
8325 2020-12-12 21:00:00              194.6                  1.8
8326 2020-12-12 22:00:00              223.9                    1
8327 2020-12-12 23:00:00              236.6                  1.2

[2929 rows x 3 columns]

In [92]:
wind_subset["bellville_wind_dir"] = pd.to_numeric(wind_subset["bellville_wind_dir"])
wind_subset["bellville_wind_speed"] = pd.to_numeric(wind_subset["bellville_wind_speed"])

C:\Users\YomelelaLornaMgwebi\AppData\Local\Temp\ipykernel_6852\4141437361.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wind_subset["bellville_wind_dir"] = pd.to_numeric(wind_subset["bellville_wind_dir"])
C:\Users\YomelelaLornaMgwebi\AppData\Local\Temp\ipykernel_6852\4141437361.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wind_subset["bellville_wind_speed"] = pd.to_numeric(wind_subset["bellville_wind_speed"])

In [93]:
wind_subset = wind_subset.reset_index(drop=True)

In [94]:
wind_subset

               timestamp  bellville_wind_dir  bellville_wind_speed
0    2020-01-01 00:00:00               191.0                   2.5
1    2020-01-01 01:00:00               209.7                   1.6
2    2020-01-01 02:00:00               202.5                   1.4
3    2020-01-01 03:00:00               224.7                   1.2
4    2020-01-01 04:00:00               244.3                   1.3
...                  ...                 ...                   ...
2924 2020-12-12 19:00:00               171.3                   2.3
2925 2020-12-12 20:00:00               174.2                   2.1
2926 2020-12-12 21:00:00               194.6                   1.8
2927 2020-12-12 22:00:00               223.9                   1.0
2928 2020-12-12 23:00:00               236.6                   1.2

[2929 rows x 3 columns]

#### joinining the subsmaple and wind subset 
- the two sets have different time location to each other this thus caused  a problem joining them
-   changed the time data time to be naitive time zones that actually communicate to each other to do the join
-   merged the file  to get the merged file 
-  dropped the columns with no speed and direction of wind

In [80]:
subsample

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index,dist_to_centroid
6,400588369,NaN,2020-10-23 10:33:48+02:00,2020-10-26 14:16:49+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,GLENHAVEN,-33.917996,18.658031,88ad361a19fffff,1.484676
15,400589257,9.109617e+09,2020-10-27 11:36:55+02:00,2020-11-11 07:39:11+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,SACK'S CIRCLE INDUSTRIA,-33.924853,18.654994,88ad361125fffff,1.483197
22,400586554,9.109558e+09,2020-10-16 14:41:42+02:00,2020-10-26 14:15:30+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Manhole Cover/Gully Grid,NaN,NaN,BELLVILLE SOUTH,-33.918566,18.639464,88ad361127fffff,0.289354
68,400598644,NaN,2020-12-01 10:28:54+02:00,2021-02-05 08:11:05+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,NaN,NaN,KEMPENVILLE,-33.901597,18.636384,88ad361ac5fffff,1.790969
73,400554944,NaN,2020-07-09 14:42:01+02:00,2020-07-16 10:31:11+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Flooding Road/Property/Informal Set,NaN,NaN,BELLVILLE CBD,-33.904904,18.632356,88ad361ac1fffff,1.613719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940948,1016507656,9.109974e+09,2020-12-31 12:29:29+02:00,2021-01-01 11:54:32+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,BELLVILLE SOUTH,-33.919625,18.648965,88ad361125fffff,0.706281
940950,1016507658,9.109974e+09,2020-12-31 12:29:54+02:00,2021-01-08 09:37:41+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Debt Management,NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681
941054,1016507773,9.109974e+09,2020-12-31 12:40:49+02:00,2021-01-11 15:34:51+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Reconnect (Non - Payment),NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681
941453,1016508221,9.109974e+09,2020-12-31 18:56:43+02:00,2020-12-31 20:09:12+02:00,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,None/Private,BELLVILLE SOUTH,-33.921359,18.641689,88ad361127fffff,0.483362
941571,1016508355,9.109974e+09,2020-12-31 21:02:26+02:00,2021-01-07 12:59:36+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,Loss,No Cause Observed,BELLVILLE SOUTH,-33.920207,18.637990,88ad361127fffff,0.511469

In [96]:
subsample["creation_timestamp"] = pd.to_datetime(subsample["creation_timestamp"], errors="coerce")

In [97]:
merged = pd.merge_asof(
    subsample.sort_values("creation_timestamp"),
    wind_subset,
    left_on="creation_timestamp",
    right_on="timestamp",
    direction="backward",
    tolerance=pd.Timedelta("1h")
)

MergeError: incompatible merge keys [0] datetime64[ns, UTC+02:00] and dtype('<M8[ns]'), must be the same type

In [ ]:

subsample["creation_timestamp"] = pd.to_datetime(
    subsample["creation_timestamp"], errors="coerce"
).dt.tz_localize(None)   

wind_subset["timestamp"] = pd.to_datetime(
    wind_subset["timestamp"], errors="coerce"
).dt.tz_localize(None)

In [99]:
subsample = subsample.dropna(subset=["creation_timestamp"])
wind_subset = wind_subset.dropna(subset=["timestamp"])

In [100]:
subsample = subsample.sort_values("creation_timestamp").reset_index(drop=True)
wind_subset = wind_subset.sort_values("timestamp").reset_index(drop=True)

In [102]:
merged5 = pd.merge_asof(
    subsample,
    wind_subset,
    left_on="creation_timestamp",
    right_on="timestamp",
    direction="backward",
    tolerance=pd.Timedelta("1h")
)

In [103]:
merged5

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index,dist_to_centroid,timestamp,bellville_wind_dir,bellville_wind_speed
0,1015463466,9.108191e+09,2020-01-01 01:49:58,2020-01-02 07:31:40+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,LABIANCE,-33.911720,18.654891,88ad361a11fffff,1.328786,2020-01-01 01:00:00,209.7,1.6
1,1015463482,9.108191e+09,2020-01-01 02:19:27,2020-01-29 15:26:22+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,BELLVILLE SOUTH,-33.918821,18.642055,88ad361127fffff,0.200577,2020-01-01 02:00:00,202.5,1.4
2,1015463542,NaN,2020-01-01 06:42:56,2020-01-02 07:34:55+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY TECHNICAL COMPLAINTS,Identify Cables,NaN,NaN,BELLVILLE SOUTH,-33.918413,18.634889,88ad361ac9fffff,0.672844,2020-01-01 06:00:00,219.7,1.8
3,1015463609,9.108191e+09,2020-01-01 09:15:36,2020-01-02 09:17:51+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,BELRAIL,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
4,1015463642,9.108191e+09,2020-01-01 09:21:04,2020-01-16 14:20:21+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,BELRAIL,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7860,1016507658,9.109974e+09,2020-12-31 12:29:54,2021-01-08 09:37:41+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Debt Management,NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681,NaT,NaN,NaN
7861,1016507773,9.109974e+09,2020-12-31 12:40:49,2021-01-11 15:34:51+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY FINANCIAL AND METER READING,Reconnect (Non - Payment),NaN,NaN,DE LA HAYE,-33.904166,18.654692,88ad361a17fffff,1.848681,NaT,NaN,NaN
7862,1016508221,9.109974e+09,2020-12-31 18:56:43,2020-12-31 20:09:12+02:00,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,None/Private,BELLVILLE SOUTH,-33.921359,18.641689,88ad361127fffff,0.483362,NaT,NaN,NaN
7863,1016508355,9.109974e+09,2020-12-31 21:02:26,2021-01-07 12:59:36+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,Loss,No Cause Observed,BELLVILLE SOUTH,-33.920207,18.637990,88ad361127fffff,0.511469,NaT,NaN,NaN
7864,1016508340,9.109974e+09,2020-12-31 21:15:17,2020-12-31 21:18:19+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,WATER,Burst Pipe,NaN,NaN,BELLVILLE SOUTH,-33.920085,18.638435,88ad361127fffff,0.472780,NaT,NaN,NaN

In [107]:
# Drop rows where wind direction or speed is missing
clean_wind_subsample = merged5.dropna(subset=["bellville_wind_dir", "bellville_wind_speed"]).reset_index(drop=True)

In [108]:
clean_wind_subsample

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index,dist_to_centroid,timestamp,bellville_wind_dir,bellville_wind_speed
0,1015463466,9.108191e+09,2020-01-01 01:49:58,2020-01-02 07:31:40+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,LABIANCE,-33.911720,18.654891,88ad361a11fffff,1.328786,2020-01-01 01:00:00,209.7,1.6
1,1015463482,9.108191e+09,2020-01-01 02:19:27,2020-01-29 15:26:22+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,BELLVILLE SOUTH,-33.918821,18.642055,88ad361127fffff,0.200577,2020-01-01 02:00:00,202.5,1.4
2,1015463542,NaN,2020-01-01 06:42:56,2020-01-02 07:34:55+02:00,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY TECHNICAL COMPLAINTS,Identify Cables,NaN,NaN,BELLVILLE SOUTH,-33.918413,18.634889,88ad361ac9fffff,0.672844,2020-01-01 06:00:00,219.7,1.8
3,1015463609,9.108191e+09,2020-01-01 09:15:36,2020-01-02 09:17:51+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,BELRAIL,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
4,1015463642,9.108191e+09,2020-01-01 09:21:04,2020-01-16 14:20:21+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,BELRAIL,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,1016459226,9.109892e+09,2020-12-12 00:45:42,2020-12-14 10:40:58+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Manhole Cover: Stolen/Missing,NaN,NaN,SAXON INDUSTRIAL,-33.917745,18.642841,88ad361127fffff,0.113008,2020-12-12 00:00:00,269.2,1.2
2951,1016459318,9.109892e+09,2020-12-12 07:46:02,2020-12-12 11:55:04+02:00,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,Short Circuit,GLENHAVEN,-33.914377,18.654861,88ad361a1bfffff,1.223966,2020-12-12 07:00:00,137.5,1.9
2952,1016459482,9.109892e+09,2020-12-12 09:01:53,2020-12-14 16:41:33+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,BELLVILLE SOUTH,-33.911549,18.641112,88ad361acdfffff,0.613455,2020-12-12 09:00:00,133.1,2.7
2953,1016459738,9.109892e+09,2020-12-12 11:20:22,2020-12-14 10:42:52+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,BELLVILLE SOUTH,-33.915194,18.637551,88ad361ac9fffff,0.456629,2020-12-12 11:00:00,155.6,2.3
2954,1016460446,9.109893e+09,2020-12-12 21:50:24,2021-01-21 12:28:00+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,NaN,NaN,BELLVILLE SOUTH,-33.918301,18.643297,88ad361127fffff,0.187142,2020-12-12 21:00:00,194.6,1.8

## Annonymize the data

In [109]:
data = clean_wind_subsample.copy()

In [111]:
columns_to_drop = [
    "notification_number",
    "reference_number",
    "official_suburb",  # could narrow to specific household
    "completion_timestamp"
]
data = data.drop(columns=[col for col in columns_to_drop if col in data.columns])

In [112]:
data

,creation_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,latitude,longitude,h3_level8_index,dist_to_centroid,timestamp,bellville_wind_dir,bellville_wind_speed
0,2020-01-01 01:49:58,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,-33.911720,18.654891,88ad361a11fffff,1.328786,2020-01-01 01:00:00,209.7,1.6
1,2020-01-01 02:19:27,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,-33.918821,18.642055,88ad361127fffff,0.200577,2020-01-01 02:00:00,202.5,1.4
2,2020-01-01 06:42:56,ENERGY,Electricity Generation and Distribution,Electricity Retail Management,Customer Support Services and Rev Man,ELECTRICITY TECHNICAL COMPLAINTS,Identify Cables,NaN,NaN,-33.918413,18.634889,88ad361ac9fffff,0.672844,2020-01-01 06:00:00,219.7,1.8
3,2020-01-01 09:15:36,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
4,2020-01-01 09:21:04,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,NaN,NaN,-33.904373,18.635651,88ad361ac5fffff,1.522730,2020-01-01 09:00:00,186.9,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,2020-12-12 00:45:42,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Manhole Cover: Stolen/Missing,NaN,NaN,-33.917745,18.642841,88ad361127fffff,0.113008,2020-12-12 00:00:00,269.2,1.2
2951,2020-12-12 07:46:02,ENERGY,Electricity Generation and Distribution,Enterprise Asset Management,CTE Distribution East,ELECTRICITY TECHNICAL COMPLAINTS,No Power,Point of Supply,Short Circuit,-33.914377,18.654861,88ad361a1bfffff,1.223966,2020-12-12 07:00:00,137.5,1.9
2952,2020-12-12 09:01:53,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,-33.911549,18.641112,88ad361acdfffff,0.613455,2020-12-12 09:00:00,133.1,2.7
2953,2020-12-12 11:20:22,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,-33.915194,18.637551,88ad361ac9fffff,0.456629,2020-12-12 11:00:00,155.6,2.3
2954,2020-12-12 21:50:24,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Burst Pipe,NaN,NaN,-33.918301,18.643297,88ad361127fffff,0.187142,2020-12-12 21:00:00,194.6,1.8