In [ ]:
!pip install boto3 pandas geopandas shapely fiona h3 requests psutil

In [2]:
import boto3
import json
import time

## Data Extraction

In [3]:
# AWS LOGINS
session = boto3.Session(
    aws_access_key_id="AKIAYH57YDEWMHW2ESH2",
    aws_secret_access_key="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",
    region_name="af-south-1"
)

s3 = session.client("s3") # S3 BUCKET

bucket = "cct-ds-code-challenge-input-data"
key = "city-hex-polygons-8-10.geojson"

# AWS SELECT STATEMENT
expression = "SELECT * FROM S3Object s WHERE s.resolution = '8'"  # using the  select statement didn't help me much, I ran into errors ,

In [4]:
start = time.time()

In [5]:
s_3 = session.client("s3")
bucket = "cct-ds-code-challenge-input-data"
key = "city-hex-polygons-8-10.geojson"

# Download file
obj = s_3 .get_object(Bucket=bucket, Key=key)
data = json.loads(obj['Body'].read())

because the select statement wasn't working to my advantage; I filtered through the data using python syntax
I chnaged the properties column to a str so that i can be able  get resolution 8 data properly

In [6]:
# Filter features with resolution = 8
features_res8 = [
    f for f in data["features"]
    if str(f["properties"].get("resolution")) == "8"
]

In [7]:
len(features_res8) # checking number of rows found here

3832

In [8]:
print(features_res8[0])

{'type': 'Feature', 'properties': {'index': '88ad361801fffff', 'centroid_lat': -33.859427322761434, 'centroid_lon': 18.677843311941835, 'resolution': 8}, 'geometry': {'type': 'Polygon', 'coordinates': [[[18.6811898997334, -33.86330279081797], [18.683574296194426, -33.85928287732969], [18.68022760998973, -33.85540739558428], [18.67449676770625, -33.855551865779326], [18.672112346191998, -33.85957172360946], [18.675458791982372, -33.8634471669068], [18.6811898997334, -33.86330279081797]]]}}

Making t

In [9]:
import geopandas as gpd
from shapely.geometry import shape

# Convert features into a list of dicts (properties + geometry)
records = []
for f in features_res8:
    props = f["properties"].copy()  # copy properties dict
    props["geometry"] = shape(f["geometry"])  # shapely polygon
    records.append(props)

# Create GeoDataFrame
geodf = gpd.GeoDataFrame(records, geometry="geometry")

In [10]:
geodf.head(10000)

,index,centroid_lat,centroid_lon,resolution,geometry
0,88ad361801fffff,-33.859427,18.677843,8,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,8,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,8,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,8,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,8,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,8,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,8,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,8,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,8,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,8,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

This is the validation, what we call "source of truth"

In [11]:
bucket2 = "cct-ds-code-challenge-input-data"
key2 = "city-hex-polygons-8.geojson"
out_file = "city-hex-polygons-8.geojson"

s3.download_file(bucket2, key2, out_file)

In [12]:
#import geopandas as valid_df
valid_df = gpd.read_file("city-hex-polygons-8.geojson")
valid_df.head(10000)

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

### Data validation

for starters: The data I xtracted from aws and the validation data they have the same number of row

In [13]:
# taking the column names that are the same as my validation set
extract_df = geodf[['index', 'centroid_lat', 'centroid_lon', 'geometry']]

In [14]:
extract_df

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

In [15]:
valid_df

,index,centroid_lat,centroid_lon,geometry
0,88ad361801fffff,-33.859427,18.677843,"POLYGON ((18.68119 -33.8633, 18.68357 -33.8592..."
1,88ad361803fffff,-33.855696,18.668766,"POLYGON ((18.67211 -33.85957, 18.6745 -33.8555..."
2,88ad361805fffff,-33.855263,18.685959,"POLYGON ((18.68931 -33.85914, 18.69169 -33.855..."
3,88ad361807fffff,-33.851532,18.676881,"POLYGON ((18.68023 -33.85541, 18.68261 -33.851..."
4,88ad361809fffff,-33.867322,18.678806,"POLYGON ((18.68215 -33.8712, 18.68454 -33.8671..."
...,...,...,...,...
3827,88ad369715fffff,-34.353404,18.479198,"POLYGON ((18.48255 -34.35726, 18.48494 -34.353..."
3828,88ad369717fffff,-34.349672,18.470112,"POLYGON ((18.47346 -34.35353, 18.47585 -34.349..."
3829,88ad369733fffff,-34.337717,18.477288,"POLYGON ((18.48063 -34.34158, 18.48303 -34.337..."
3830,88ad369739fffff,-34.349293,18.487330,"POLYGON ((18.49068 -34.35315, 18.49307 -34.349..."
3831,88ad36973bfffff,-34.345561,18.478243,"POLYGON ((18.48159 -34.34942, 18.48398 -34.345..."

I then used an inner join to check if we have similar data with the validation set

In [16]:
common = extract_df.merge(valid_df, how='inner')
print(f"{len(common)} rows in aws extract are also in validation extract")
#common.head()

3832 rows in aws extract are also in validation extract

an extra check for those not on the other and now I switched data around

In [17]:
valid_df.geometry

0       POLYGON ((18.68119 -33.8633, 18.68357 -33.8592...
1       POLYGON ((18.67211 -33.85957, 18.6745 -33.8555...
2       POLYGON ((18.68931 -33.85914, 18.69169 -33.855...
3       POLYGON ((18.68023 -33.85541, 18.68261 -33.851...
4       POLYGON ((18.68215 -33.8712, 18.68454 -33.8671...
                              ...
3827    POLYGON ((18.48255 -34.35726, 18.48494 -34.353...
3828    POLYGON ((18.47346 -34.35353, 18.47585 -34.349...
3829    POLYGON ((18.48063 -34.34158, 18.48303 -34.337...
3830    POLYGON ((18.49068 -34.35315, 18.49307 -34.349...
3831    POLYGON ((18.48159 -34.34942, 18.48398 -34.345...
Name: geometry, Length: 3832, dtype: geometry

In [18]:
diff = valid_df[~valid_df['index'].isin(extract_df['index'])]
print(f"{len(diff)} rows in the aws extract are NOT in validation data")

0 rows in the aws extract are NOT in validation data

## Initial Transformation

In [19]:
import pandas as pd

In [20]:
df_sr = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr.csv")

In [21]:
df_sr.head()

,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude
0,0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488
1,1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940
2,2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116
3,3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209
4,4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760

In [22]:
merged_df2 = extract_df.merge(
    df_sr,
    left_on=['centroid_lat', 'centroid_lon'],
    right_on=['latitude', 'longitude'],
    how='inner'
)

In [23]:
merged_df2

Empty GeoDataFrame
Columns: [index, centroid_lat, centroid_lon, geometry, Unnamed: 0, notification_number, reference_number, creation_timestamp, completion_timestamp, directorate, department, branch, section, code_group, code, cause_code_group, cause_code, official_suburb, latitude, longitude]
Index: []

In [24]:
print(extract_df.iloc[0].geometry)

POLYGON ((18.6811898997334 -33.86330279081797, 18.683574296194426 -33.85928287732969, 18.68022760998973 -33.85540739558428, 18.67449676770625 -33.855551865779326, 18.672112346191998 -33.85957172360946, 18.675458791982372 -33.8634471669068, 18.6811898997334 -33.86330279081797))

In [25]:
rows = []
for i, row in extract_df.iterrows():
    polygon = row.geometry
    for lon, lat in polygon.exterior.coords:   # get outer ring vertices
        rows.append({
            "index": row["index"],             # keep polygon ID
            "longitude": lon,
            "latitude": lat
        })

coords_df = pd.DataFrame(rows)

In [26]:
coords_df

                 index  longitude   latitude
0      88ad361801fffff  18.681190 -33.863303
1      88ad361801fffff  18.683574 -33.859283
2      88ad361801fffff  18.680228 -33.855407
3      88ad361801fffff  18.674497 -33.855552
4      88ad361801fffff  18.672112 -33.859572
...                ...        ...        ...
26819  88ad36973bfffff  18.480635 -34.341576
26820  88ad36973bfffff  18.474896 -34.341703
26821  88ad36973bfffff  18.472504 -34.345687
26822  88ad36973bfffff  18.475851 -34.349546
26823  88ad36973bfffff  18.481590 -34.349420

[26824 rows x 3 columns]

In [27]:
merged_df3 = coords_df.merge(
    df_sr,
    on=["longitude", "latitude"],
    how="inner"
)

In [28]:
merged_df3.head

<bound method NDFrame.head of Empty DataFrame
Columns: [index, longitude, latitude, Unnamed: 0, notification_number, reference_number, creation_timestamp, completion_timestamp, directorate, department, branch, section, code_group, code, cause_code_group, cause_code, official_suburb]
Index: []>

new

In [29]:
from shapely.geometry import Point
import time, logging

logging.basicConfig(level=logging.INFO)

start_time = time.time()


requests_df = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr.csv")        # service requests

# 2. Make requests GeoDataFrame
requests_gdf = gpd.GeoDataFrame(
    requests_df,
    geometry=[Point(xy) if pd.notna(xy[0]) and pd.notna(xy[1]) else None 
              for xy in zip(requests_df["longitude"], requests_df["latitude"])],
    crs="EPSG:4326"
)

In [31]:
valid_df = valid_df[["index","geometry"]].copy()
requests_gdf = requests_gdf[["geometry"] + [col for col in requests_gdf.columns if col != "geometry"]]

joined = gpd.sjoin(requests_gdf, valid_df, how="left", predicate="within")

In [32]:
joined

,geometry,Unnamed: 0,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,index_right0,index
0,POINT (18.52249 -33.87284),0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488,1047.0,88ad360225fffff
1,POINT (18.84894 -34.07892),1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940,3055.0,88ad36d5e1fffff
2,POINT (18.82112 -34.10224),2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116,2946.0,88ad36d437fffff
3,POINT (18.60721 -33.92002),3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209,1247.0,88ad361133fffff
4,POINT (18.45376 -33.9874),4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760,2530.0,88ad361709fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941629,POINT (18.45216 -33.93157),941629,1016508425,9.109974e+09,2020-12-31 23:49:38+02:00,2021-01-11 11:54:42+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,WOODSTOCK,-33.931571,18.452159,2439.0,88ad361547fffff
941630,POINT (18.71655 -33.78325),941630,1016508432,9.109975e+09,2020-12-31 23:31:11+02:00,2021-01-04 11:46:28+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,FISANTEKRAAL,-33.783246,18.716554,542.0,88ad3656d7fffff
941631,None,941631,1016508434,9.109975e+09,2020-12-31 23:58:21+02:00,2021-01-01 00:01:08+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,WATER,Burst Pipe,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941632,POINT (18.65983 -33.9711),941632,1016508442,9.109975e+09,2020-12-31 23:41:57+02:00,2021-01-05 15:59:24+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,WESBANK,-33.971099,18.659831,1502.0,88ad36c49bfffff
941633,POINT (18.86255 -34.08808),941633,1016508443,9.109975e+09,2020-12-31 23:54:09+02:00,2021-02-23 10:38:21+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER,Leak at Water Meter / Stopcock,NaN,NaN,BIZWENI,-34.088078,18.862550,2974.0,88ad36d517fffff

### data validation

In [33]:
df_val = pd.read_csv(r"C:\Users\YomelelaLornaMgwebi\Downloads\awstrial\sr_hex.csv")

In [34]:
df_val

,notification_number,reference_number,creation_timestamp,completion_timestamp,directorate,department,branch,section,code_group,code,cause_code_group,cause_code,official_suburb,latitude,longitude,h3_level8_index
0,400583534,9.109492e+09,2020-10-07 06:55:18+02:00,2020-10-08 15:36:35+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area Central,District: Blaauwberg,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Wear and tear,MONTAGUE GARDENS,-33.872839,18.522488,88ad360225fffff
1,400555043,9.108995e+09,2020-07-09 16:08:13+02:00,2020-07-14 14:27:01+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,SOMERSET WEST,-34.078916,18.848940,88ad36d5e1fffff
2,400589145,9.109614e+09,2020-10-27 10:21:59+02:00,2020-10-28 17:48:15+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area East,District : Somerset West,TD Customer complaint groups,Manhole Cover/Gully Grid,Road (RCL),Vandalism,STRAND,-34.102242,18.821116,88ad36d437fffff
3,400538915,9.108601e+09,2020-03-19 06:36:06+02:00,2021-03-29 20:34:19+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area North,District : Bellville,TD Customer complaint groups,Paint Markings Lines&Signs,Road Markings,Wear and tear,RAVENSMEAD,-33.920019,18.607209,88ad361133fffff
4,400568554,NaN,2020-08-25 09:48:42+02:00,2020-08-31 08:41:13+02:00,URBAN MOBILITY,Roads Infrastructure Management,RIM Area South,District : Athlone,TD Customer complaint groups,Pothole&Defect Road Foot Bic Way/Kerbs,Road (RCL),Surfacing failure,CLAREMONT,-33.987400,18.453760,88ad361709fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941629,1016508425,9.109974e+09,2020-12-31 23:49:38+02:00,2021-01-11 11:54:42+02:00,WATER AND SANITATION,Distribution Services,Reticulation,Reticulation Water Distribution,WATER,Leak at Valve,NaN,NaN,WOODSTOCK,-33.931571,18.452159,88ad361547fffff
941630,1016508432,9.109975e+09,2020-12-31 23:31:11+02:00,2021-01-04 11:46:28+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,SEWER,Sewer: Blocked/Overflow,General,Foreign Objects,FISANTEKRAAL,-33.783246,18.716554,88ad3656d7fffff
941631,1016508434,9.109975e+09,2020-12-31 23:58:21+02:00,2021-01-01 00:01:08+02:00,WATER AND SANITATION,Distribution Services,Reticulation,NaN,WATER,Burst Pipe,NaN,NaN,NaN,NaN,NaN,0
941632,1016508442,9.109975e+09,2020-12-31 23:41:57+02:00,2021-01-05 15:59:24+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER MANAGEMENT DEVICE,No Water WMD,NaN,NaN,WESBANK,-33.971099,18.659831,88ad36c49bfffff
941633,1016508443,9.109975e+09,2020-12-31 23:54:09+02:00,2021-02-23 10:38:21+02:00,WATER AND SANITATION,Commercial Services,Customer Services (Water),Meter Management,WATER,Leak at Water Meter / Stopcock,NaN,NaN,BIZWENI,-34.088078,18.862550,88ad36d517fffff

In [35]:
merged_df4 = df_val.merge(
    joined,
    on=["notification_number"],
    how="inner"
)

In [ ]:
print(f"{len(merged_df4)} rows in joined data are also in validation extract")

941634 rows in aws extract are also in validation extract

## Further transformations

### one minute away from bellville